# ------------------TABUADA---------------------------- #
import time
import os
print('-=-' *15)
print('!!!TABUADA DE TERMINAL!!!')
print('-=-' * 15)
time.sleep(2)
t = int(input('digite um numero para ver sua tabuada:'))
time.sleep(2)
print('PROCESSANDO...')
time.sleep(1.5)
print('=' *15)
print('{} x  {} = {}'.format(t, 1 , t*1))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 2 , t*2))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 3 , t*3))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 4 , t*4))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 5 , t*5))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 6 , t*6))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 7 , t*7))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 8 , t*8))
time.sleep(1.5)
print('{} x  {} = {}'.format(t, 9 , t*9))
time.sleep(1.5)
print('{} x {} = {}'.format(t, 10 , t*10))
print('=' *15)
time.sleep(1.5)
print('!!!OBRIGADO POR USAR ESSE PROGRAMA!!!')
time.sleep(1.5)
print('REINICIANDO...')
time.sleep(5)
os.system('cls')
# ------------------FIM-------------------------------- #